# Generated by Django 3.2 on 2021-04-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='nama@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='judul',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
